name: Publish to public repo

on:
  push:
    branches: [main]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout private repo
        uses: actions/checkout@v4

      - name: Push to public repo
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.PUBLISH_TOKEN }}
        with:
          source-directory: '.'
          destination-github-username: 'partyfix'
          destination-repository-name: 'partyfix-data-public'
          target-branch: main
          exclude-paths: '.github'
